#!/bin/sh
set -eu

project_root="$1"
output_dir="$2"

# Prefer the actual checkout (including a PR merge commit) over CI event metadata.
commit="$(git -C "$project_root" rev-parse --short HEAD 2>/dev/null || true)"
if [ -z "$commit" ]; then
    commit="${GITHUB_SHA:-}"
fi
# Only a hash may be embedded in the generated Swift source.
case "$commit" in
    ''|*[!0-9a-fA-F]*) commit="Unavailable" ;;
    *) commit="$(printf '%s' "$commit" | cut -c1-12)" ;;
esac
build_date="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"

mkdir -p "$output_dir"
cat > "$output_dir/BuildMetadata.swift" <<EOF
// Generated by BuildMetadataPlugin. Do not edit.
enum BuildMetadata {
    static let commit = "$commit"
    static let date = "$build_date"
}
EOF
